# Generated by Django 2.2.5 on 2019-09-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('query', models.TextField(null=True)),
            ],
        ),
    ]
